### ISSUE TITLE
iOS SpreedMe app does not work when the Two Factor TOTP Provider is activated on a account

### ISSUE THREAD

**Issue by kaksikanaa** [strukturag/webrtc-ios#1]
Not sure is this issue on the SpreedMe app or server or Nextcloud server -> 
When I install and activate the Two Factor TOTP Provider on Nextcloud and on my account, the TOTP works with files etc. but not with SpreedMe app on the iOS because the authentication fails afterwards  every time with old password or with the new separately generated App password as well. 

Any body else have this issue?

**Comment by kaksikanaa** [comment]
Still having this issue. Could someone confirm that TOTP is supported on the SpreedME app?

**Comment by Ivansss** [comment]
@kaksikanaa sorry for the late reply.
Spreed.ME iOS app does not support TOTP at this moment.

**Comment by kaksikanaa** [comment]
Ok.
